### PR TITLE
Firefox

### PR DESCRIPTION
**Pull request by ChristophHess**
Hey Ben,

since I really liked your extension for chrome and was not able to find anything equally good for Firefox I ported the add-on.
It's still using your build process though I had to update the build.xml.
I tested most features according to the QA.txt but I'm not sure if the new plugin works in Chrome also.
I had to update jQuery to a new Version since Mozilla will not allow the old version due to security concerns.
The one feature I had to remove was the option for focus/blur on new window since Firefox does not support that param.
I will test the Chrome compatibility in the coming days but right now I need sleep. I hope I didn't miss anything.

Best regards and thanks for your work on this add-on
Chris

Edit: Links to issue #96

### CODE REVIEW

**Comment by ChristophHess** [comment]
#160 #96

**Comment by benblack86** [comment]
This PR contains a lot of changes. Most seem to be formatting changes, which shouldn't have been done without first defining the standard. The formatting changes make it difficult to see what you have done to make it work on firefox.

My other concern is who is going to submit to firefox? I don't have time to do that.

**Comment by ChristophHess** [comment]
You're right. I might have been a bit generous with my code auto-formatting. It's become muscle memory. I can go back and remove the code formatting and resubmit a pull request if you want.

**Comment by ChristophHess** [comment]
Also I don't mind publishing to Mozilla.

**Pull request closed without merging**
