### PR TITLE
Made linkclump ready for manifest V3

### PR DESCRIPTION
**Pull request by wvanderp**
I have been working on updating linkclump for manifest V3 since I use it a ton, and I miss it dearly.

I changed a lot more than intended and thus wanted some feedback on whether you are willing to accept it or if I should tone it down.

A rundown of the changes:

- Updated the manifest to use the new V3 style.
- I replaced the removed Chrome extension functions with the new ones.
- I needed some help to get all the types straight, so I introduced typescript
  - at first, to check the JS, but then I buckled and started writing real typescript
- Then, I needed Babel to compile the typescript to JS
- Which introduced Webpack to build the code
- Then I went crazy on the code to get it all to work right
  - I moved all of the var to the window scope
  - Squashed most of the possible undefined or null cases
  - And generally linted the files

I totally understand if you want to keep the project JS only. In that case, I can strip all the types from the files and deliver regular JS files.

The only thing left to do is to test the new build thoroughly. When it's clear what option you prefer, I intend to test the build and deliver the final PR.

I'm happy to oblige if you have any questions or change requests.
I'm excited to hear from you, and I hope you can accept this PR to ensure we can use Linkclump in the future.

### CODE REVIEW

**Comment by benblack86** [comment]
I no longer have time to maintain Linkclump. I think the best way forward is to publish a new extension that conforms to the latest manifest. Feel free to fork Linkclump or just copy the ideas. Once Google removes Linkclump from the website, I'll mark this repo as archived.

**Comment by wvanderp** [comment]
I can create a linkclump-ng that is a fork of your original and will be based on this PR. 

I'm hesitant to suggest this, but it is possible to transfer Chrome extensions.
I can take over ownership and publish and maintain the new version.
My main hesitation is that I fear rejection because I just waltzed in here and did not build any trust.

Another version of this could be that I maintain the code, and the only thing you have to do is publish the new versions.

I would be happy to carry on the torch. And keeping the same extension up would benefit everyone who has already found Linkclump.

I am interested to hear your thoughts.

**Comment by benblack86** [comment]
I would prefer it if you create a new extension rather than transferring ownership, that way we can let people decide whether or not they want to move.

**Comment by pnlrogue1** [comment]
@wvanderp please do continue the project with Manifest V3! I love this extension and it makes various things I do so much easier!

I would love to offer to help but sadly I know almost zero JavaScript and even less TypeScripts (I'm a Systems Engineer not a Software Engineer). Happy to do the occasional test for you if I can!

**Comment by fede777** [comment]
For anyone looking for an alternative, there's 2 forks of this extension that are MV3 compatible.

https://chromewebstore.google.com/detail/linkclump-pro/hfollkhbdmgdnakpgocoldgdjaoahhni
https://chromewebstore.google.com/detail/linkclump-plus/ainlglbojoodfdbndbfofojhmjbmelmm

**Pull request closed without merging**
